# Generated by Django 6.0.3 on 2026-03-30 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0004_remove_casino_page_id_casino_fb_page_access_token_and_more'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fb_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacebookOutgoingMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100)),
                ('recipient_fb_user_id', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('matched', models.BooleanField(default=False)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_outgoing_logs', to='casinos.casino')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_outgoing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
