# Generated by Django 6.0.3 on 2026-03-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0004_remove_casino_page_id_casino_fb_page_access_token_and_more'),
        ('customer', '0003_alter_transaction_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='casinos.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='casinos.platforms'),
        ),
    ]
