# Generated by Django 6.0.3 on 2026-03-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
