# Generated by Django 6.0.3 on 2026-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_staff_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_user_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
