# Generated by Django 6.0.3 on 2026-03-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_fb_user_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_oauth_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
