# Generated by Django 6.0.3 on 2026-04-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_fb_oauth_state'),
        ('casinos', '0005_rename_fb_page_id_casino_chatwoot_inbox_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_casino_admin_per_casino',
        ),
        migrations.AddField(
            model_name='user',
            name='casinos',
            field=models.ManyToManyField(blank=True, related_name='users', to='casinos.casino'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='casino',
        ),
    ]
