# Generated by Django 6.0.3 on 2026-04-24 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='fcm_token',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='expo_token',
            field=models.TextField(default=datetime.datetime(2026, 4, 24, 19, 24, 9, 446575, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdevice',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
