# Generated by Django 6.0.3 on 2026-04-27 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userdevice_fcm_token_userdevice_expo_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='expo_token',
            new_name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='platform',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
