# Generated by Django 6.0.3 on 2026-03-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_paymentmethod_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='page_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
