# Generated by Django 6.0.3 on 2026-03-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0003_casino_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='page_id',
        ),
        migrations.AddField(
            model_name='casino',
            name='fb_page_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
