# Generated by Django 6.0.3 on 2026-04-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0004_remove_casino_page_id_casino_fb_page_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='fb_page_id',
            new_name='chatwoot_inbox_id',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='fb_page_access_token',
        ),
    ]
