# Generated by Django 6.0.3 on 2026-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0005_rename_fb_page_id_casino_chatwoot_inbox_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='fb_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='fb_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
